/* Even Fibonacci numbers */

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

    const isEven = (number)=>{
          if ( number % 2 != 0) {
             return false;  
          }     
          return true; 
    }   

    const SequenceFibonacci =  (top)=>{
        let n1 = 1
        let n2 = 2
        let fibonacci = [n1,n2]
    
        for (let i = 2; i < top; i++) {
            
                let elemento = n2 + n1
                if (elemento < 4000000) {
                    fibonacci.push(elemento) 
                    n1 = n2 
                    n2 = elemento
                }
                
            

             
        }

       return fibonacci  
    } 

    const SumEvenFibonacci = (serie)=> {
         
            let sum=0;
            serie.forEach(element => {

                if (isEven(element)) {
                    sum+=element 
                }

                   
                
                   
            });
           return sum;
    }

console.log( SumEvenFibonacci( SequenceFibonacci(400000)))   

   

